### ISSUE TITLE
Decrease the line-height and size.

### ISSUE THREAD

**Issue by Sajid-Ali-com** [Sajid-Ali-com/PrimeHub#11]
https://www-computan-com.sandbox.hs-sites.com/primehub/home-b

![image](https://user-images.githubusercontent.com/45878214/234843783-acec50cf-c016-4101-8770-667749115efb.png)

**Comment by jeremiah-amir-com** [comment]
Updated.

**Comment by Sajid-Ali-com** [comment]
Should be 18px.

**Comment by jeremiah-amir-com** [comment]
Updated
