### ISSUE TITLE
Decrease the size and add the icons.

### ISSUE THREAD

**Issue by Sajid-Ali-com** [Sajid-Ali-com/PrimeHub#13]
https://www-computan-com.sandbox.hs-sites.com/primehub/career

![image](https://user-images.githubusercontent.com/45878214/234844757-e06fc090-b7eb-43bf-bd7f-0f6d3c606528.png)

**Comment by Sajid-Ali-com** [comment]
Please add icon accordingly.

**Comment by jeremiah-amir-com** [comment]
Updated.
