### ISSUE TITLE
Decrease the font size.

### ISSUE THREAD

**Issue by Sajid-Ali-com** [Sajid-Ali-com/PrimeHub#18]
https://www-computan-com.sandbox.hs-sites.com/primehub/services-a

![image](https://user-images.githubusercontent.com/45878214/234846557-09873f53-49c8-4301-939f-53b0589e63ff.png)

Error text should be in red.

![image](https://user-images.githubusercontent.com/45878214/234846728-0e6a9222-12cb-43ab-a241-d96998d2f625.png)

**Comment by jeremiah-amir-com** [comment]
Updated
