### ISSUE TITLE
Sub Menu Text size should be decreased.

### ISSUE THREAD

**Issue by Sajid-Ali-com** [Sajid-Ali-com/PrimeHub#2]
https://www-computan-com.sandbox.hs-sites.com/primehub/home-a

![image](https://user-images.githubusercontent.com/45878214/234838135-304e9bf0-81f0-48b2-84c3-c19284b0a09e.png)

**Comment by Aamir-Aslam-com** [comment]
There was 18PX I have added 16px. Done
