### ISSUE TITLE
Decrease the font size.

### ISSUE THREAD

**Issue by Sajid-Ali-com** [Sajid-Ali-com/PrimeHub#20]
https://www-computan-com.sandbox.hs-sites.com/primehub/landing-page-fullwidth

![image](https://user-images.githubusercontent.com/45878214/234848268-919ee129-9050-4086-b45d-a30600997fb0.png)

![image](https://user-images.githubusercontent.com/45878214/234848427-9ec59861-4a57-4356-b45b-679c1cfda734.png)

![image](https://user-images.githubusercontent.com/45878214/234848619-b0610e05-ad1d-449a-a0fc-5829c61b908d.png)

**Comment by waseem-ali-com** [comment]
It was 18px I have updated to 16px.
Done

**Comment by Sajid-Ali-com** [comment]
Should be 14px

**Comment by jeremiah-amir-com** [comment]
Updated to 14px.
