### ISSUE TITLE
System pages layout issue.

### ISSUE THREAD

**Issue by Sajid-Ali-com** [Sajid-Ali-com/PrimeHub#21]
- [ ] Button should be the same and decrease the size of the button
- [ ] Input should be the same on all these pages.

https://482618.hubspotpreview-na1.com/_hcms/preview/template/multi?domain=undefined&hs_preview_key=DR_R-ggcKo3XBQmuPTuf5g&portalId=482618&tc_deviceCategory=undefined&template_file_path=PrimeHub%2Ftemplates%2Fsystem%2Fbackup-unsubscribe.html&updated=1665053163183&

https://482618.hubspotpreview-na1.com/_hcms/preview/template/multi?domain=undefined&hs_preview_key=--9sAE-iMJPWWEWG991mPQ&portalId=482618&tc_deviceCategory=undefined&template_file_path=PrimeHub%2Ftemplates%2Fsystem%2Fpassword-prompt.html&updated=1665053263933&

https://482618.hubspotpreview-na1.com/_hcms/preview/template/multi?domain=undefined&hs_preview_key=S5Eoj6Aad_1dMnfzYlLgPA&portalId=482618&tc_deviceCategory=undefined&template_file_path=PrimeHub%2Ftemplates%2Fsystem%2Fsearch-results.html&updated=1668086485102

**Comment by jeremiah-amir-com** [comment]
Updated.
