### ISSUE TITLE
Blog Listing issues.

### ISSUE THREAD

**Issue by Sajid-Ali-com** [Sajid-Ali-com/PrimeHub#22]
https://www.computan.com/primehub-blog?__hstc=233546881.720b0acac70c379483e2bf70142f73f9.1675843597169.1675843597169.1682590439303.2&__hssc=233546881.36.1682590439303&__hsfp=4238125340

- [ ] Two items in one row.
- [ ] Decrease the arrow size.
- [ ] Add the social icons.

![image](https://user-images.githubusercontent.com/45878214/234850716-91be47dd-694c-4d41-9f56-6813121ed738.png)

**Comment by touqeer-haider-com** [comment]
Done
