### ISSUE TITLE
Blog Post Issues.

### ISSUE THREAD

**Issue by Sajid-Ali-com** [Sajid-Ali-com/PrimeHub#23]
https://www.computan.com/primehub-blog/do-you-need-less-coding-skills-and-dnd-platforms

![image](https://user-images.githubusercontent.com/45878214/234851154-7789b08a-cae4-4d4d-8455-e3f7d7e65a32.png)

![image](https://user-images.githubusercontent.com/45878214/234851210-82ad9712-d569-4345-8434-636c1b290371.png)

**Comment by touqeer-haider-com** [comment]
Done

**Comment by waseem-ali-com** [comment]
Done!

**Comment by Sajid-Ali-com** [comment]
Size is still 16px should be 14px.

**Comment by touqeer-haider-com** [comment]
Updated
