### ISSUE TITLE
Fix heading alignment for all pages.

### ISSUE THREAD

**Issue by Sajid-Ali-com** [Sajid-Ali-com/PrimeHub#25]
https://www-computan-com.sandbox.hs-sites.com/primehub/about-us-b
https://www-computan-com.sandbox.hs-sites.com/primehub/about-us-c

Please check all pages.

![image](https://user-images.githubusercontent.com/45878214/235196399-d39b2650-959e-46b6-bf1f-e4032f89bfd2.png)

**Comment by jeremiah-amir-com** [comment]
Updated.
