### ISSUE TITLE
Top bottom padding should be 70px for desktop.

### ISSUE THREAD

**Issue by Sajid-Ali-com** [Sajid-Ali-com/PrimeHub#3]
https://www-computan-com.sandbox.hs-sites.com/primehub/home-a

- [ ] All sections top bottom padding should be 70px

![image](https://user-images.githubusercontent.com/45878214/234838471-3ec4c52e-3db8-4682-a0f3-8700fdbef18c.png)

**Comment by Aamir-Aslam-com** [comment]
Done
