### ISSUE TITLE
Add the correct link.

### ISSUE THREAD

**Issue by Sajid-Ali-com** [Sajid-Ali-com/PrimeHub#5]
https://www-computan-com.sandbox.hs-sites.com/primehub/home-a

- [x] Copyright Text size should be small.

![image](https://user-images.githubusercontent.com/45878214/234840338-92c3a6e7-429f-4b9e-aee1-bdb5457e694a.png)

**Comment by jeremiah-amir-com** [comment]
Added the link to the footer logo and reduced the size of the copyright text.

**Comment by Sajid-Ali-com** [comment]
More decrease copyright text.

**Comment by jeremiah-amir-com** [comment]
Updated.
